import { StyleSheet } from 'react-native';
import MainScreen from 'screens/MainScreen';

export const styles = StyleSheet.create({
  // Sign in Screen
  signIn_Container: {
    padding: 16,
  },
  signIn_Text: {
    fontSize: 28,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 16,
  },
  signIn_Input: {
    borderWidth: 1,
    marginVertical: 8,
    padding: 12,
    fontSize: 18,
    borderRadius: 8,
  },
  signIn_Touchable: {
    alignSelf: 'center',
    marginVertical: 12,
    width: 320,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#96ceb4',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 2,
    elevation: 2,
  },
  signIn_Touchable_Text: {
    color: '#111',
    fontWeight: 'bold',
    fontSize: 20,
  },
  signIn_Googlebutton: {
    alignSelf: 'center',
    marginVertical: 12,
    width: 320,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#ffeead',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 2,
    elevation: 2,
  },
  signIn_Googlebutton_image: {
    width: 32,
    height: 32,
    marginRight: 16,
  },
  signIn_Googlebutton_text: {
    color: '#111',
    fontWeight: 'bold',
    fontSize: 20,
  },
  signIn_goBackButton: {
    alignSelf: 'center',
    marginVertical: 12,
    width: 320,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#ffcc5c',
    justifyContent: 'center',
    alignItems: 'center',
  },
  signIn_goBackButton_text: {
    color: '#111',
    fontWeight: 'bold',
    fontSize: 18,
  },

  // Sign Up Page
  signUp_container: { padding: 16 },
  signUp_text: {
    fontSize: 28,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 16,
  },
  signUp_Input: {
    borderWidth: 1,
    marginVertical: 8,
    padding: 12,
    fontSize: 18,
    borderRadius: 8,
  },
  signUp_touchable: {
    alignSelf: 'center',
    marginVertical: 12,
    width: 320,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#ffcc5c',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 2,
    elevation: 2,
  },
  signUp_touchable_text: {
    color: '#111',
    fontWeight: 'bold',
    fontSize: 20,
  },
  signUp_googleButton: {
    alignSelf: 'center',
    marginVertical: 12,
    width: 320,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#ffeead',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 2,
    elevation: 2,
  },
  signUp_googleButton_image: {
    width: 32,
    height: 32,
    marginRight: 16,
  },
  signUp_googleButton_text: {
    color: '#111',
    fontWeight: 'bold',
    fontSize: 20,
  },
  signUp_signinButton: {
    alignSelf: 'center',
    marginVertical: 12,
    width: 320,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#96ceb4',
    justifyContent: 'center',
    alignItems: 'center',
  },
  signUp_signinButton_text: {
    color: '#111',
    fontWeight: 'bold',
    fontSize: 18,
  },
  signUp_Avatar_Touchable: {
    marginBottom: 16,
  },
  signUp_Avatar_Touchable_image: {
    width: 100,
    height: 100,
    borderRadius: 50,
    borderWidth: 2,
    borderColor: '#96ceb4',
    backgroundColor: '#fff',
    alignSelf: 'center',
  },
  signUp_Avatar_Touchable_text: {
    textAlign: 'center',
    fontSize: 18,
    color: '#111',
    marginTop: 8,
  },
  //Welcome Screen
  gradient: {
    flex: 1,
  },
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  text: {
    color: '#111',
    fontSize: 18,
    marginVertical: 2,
    textAlign: 'center',
  },
  inputContainer: {
    width: '100%',
    alignItems: 'center',
    marginVertical: 8,
  },
  input: {
    width: 200,
    borderWidth: 1,
    borderColor: '#111',
    borderRadius: 8,
    padding: 10,
    marginBottom: 8,
    color: '#111',
    backgroundColor: 'rgba(255,255,255,0.7)',
  },
  button: {
    marginVertical: 4,
    width: 200,
  },

  //Main Screen
  mainScreen_container: {},
  mainScreen_container_Text: { fontSize: 28, fontWeight: 'bold', textAlign: 'center' },
  tabContainer: {
    flexDirection: 'row',
    backgroundColor: '',
    justifyContent: 'space-around',
    paddingVertical: 10,
  },
  tabButton: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    // borderRadius: 20,
    opacity: 0.5,
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  activeTab: {
    // backgroundColor: '#ff6f69',
    borderBottomColor: 'black',
    opacity: 1,
  },
  tabText: {
    fontWeight: 'bold',
    color: '#111',
    fontSize: 17,
  },

  //Chore Card
  card: {
    backgroundColor: '#fff',
    padding: 16,
    marginVertical: 5,
    marginHorizontal: 16,
    borderRadius: 12,
    elevation: 3,
    position: 'relative',
  },
  rewardBadge: {
    position: 'absolute',
    top: 10,
    right: 10,
    backgroundColor: '#ff6f69',
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 20,
  },
  rewardText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 14,
  },
  choreName: {
    fontSize: 19,
    fontWeight: 'bold',
    marginBottom: 8,
    color: '#111',
  },
  assignedTo: {
    fontSize: 15,
    marginBottom: 4,
    color: '#555',
  },
  countdown: {
    fontSize: 15,
    color: '#888',
  },
  card_Done: {
    backgroundColor: 'green',
  },
  card_Doing: {
    backgroundColor: 'yellow',
  },
  card_Todo: {
    backgroundColor: '#fff',
  },
});
