#!/bin/sh
set -e
cd roomies-backend/functions

npm run build

firebase emulators:exec --only firestore,auth \
  --import=./seed \
  --export-on-exit \
  --project roomies-app-32362 -- \
  "npm test && npm run lint"
